name: threads
description: "threads clone coding"

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: 10.3.0
  firebase_core: ^3.15.2
  cloud_firestore: ^5.4.4
  firebase_storage: 12.4.10

  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1

  image_picker: ^1.0.4
  permission_handler: ^12.0.1
  image: ^4.1.3
  camera: ^0.11.2
  go_router: ^16.2.1
  video_player: ^2.10.0

  provider: ^6.1.2
  shared_preferences: ^2.3.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/Threads-Logo.png
    - assets/Threads-Logo-white.png
    - assets/transparent.png

  uses-material-design: true
