// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4p-0FLAeSxVW4CP5LlxFSmaNBzXVks4g',
    appId: '1:687283648250:web:ec758d20b072ad86623b43',
    messagingSenderId: '687283648250',
    projectId: 'thread-clone-cea4c',
    authDomain: 'thread-clone-cea4c.firebaseapp.com',
    storageBucket: 'thread-clone-cea4c.firebasestorage.app',
    measurementId: 'G-404GJEK06V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcdvDdbggmi0uMTzikNKpzS91VX29c5Cs',
    appId: '1:687283648250:android:1cab2eccac9b42ae623b43',
    messagingSenderId: '687283648250',
    projectId: 'thread-clone-cea4c',
    storageBucket: 'thread-clone-cea4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxwbDBmVCPppgEtOh1uJ0v6zrNCWNym_w',
    appId: '1:687283648250:ios:d4c828785484ddab623b43',
    messagingSenderId: '687283648250',
    projectId: 'thread-clone-cea4c',
    storageBucket: 'thread-clone-cea4c.firebasestorage.app',
    iosBundleId: 'com.example.threadClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxwbDBmVCPppgEtOh1uJ0v6zrNCWNym_w',
    appId: '1:687283648250:ios:d4c828785484ddab623b43',
    messagingSenderId: '687283648250',
    projectId: 'thread-clone-cea4c',
    storageBucket: 'thread-clone-cea4c.firebasestorage.app',
    iosBundleId: 'com.example.threadClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4p-0FLAeSxVW4CP5LlxFSmaNBzXVks4g',
    appId: '1:687283648250:web:71d4aada37836f25623b43',
    messagingSenderId: '687283648250',
    projectId: 'thread-clone-cea4c',
    authDomain: 'thread-clone-cea4c.firebaseapp.com',
    storageBucket: 'thread-clone-cea4c.firebasestorage.app',
    measurementId: 'G-G0ZT647T84',
  );
}
